### ISSUE TITLE
Problems when running on heroku or behind reverse proxy

### ISSUE THREAD

**Issue by P1-Ro** [denverquane/amongusdiscord#121]
When running on heroku (or behind reverse proxy) `PORT` isn't actually reachable from outside. It would be useful if in some scenarios `PORT` wouldn't be appended to url sent to discord.

I would suggest that if `SERVER_URL`  ends with `/` port isn't used at all.

**Comment by denverquane** [comment]
The PORT and SERVER_URL are specifically used to construct the URI sent to the user's DMs, so that the user doesn't need to enter any connect codes. But crucially, this also solves a problem for us when running the bot in sharded mode; the URI constructed by the bot points the capture client towards the **correct** shard, not just any shard.

So I'm not personally well-versed on how Heroku works, or how the port mappings within Heroku work (the instance obviously has SOME port, maybe 80 or 443? Excluding the port entirely won't solve the problem), but we really can't remove the notions of Port/Server_url without making some pretty heavy assumptions.

**Comment by jasperduijn** [comment]
I'm having the same issue. Setting the PORT parameter to 443 is not possible since the program is restricted to Ports >=1024. 

Being able to set it to 80 or 443 would solve the reverse proxy issue.

**Comment by Plysm** [comment]
I fixed this when running on Heroku by removing the appended port in the message_handlers.go file and pushing a commit to Heroku via Heroku's CLI. The solution I had is sloppy and could possibly be better if a setting or flag was added to hide/show the port in the URI but it was a way to quickly get up and running without removing the port from the URI every time.
![image](https://user-images.githubusercontent.com/49827919/95514176-831fc900-0989-11eb-89da-95817cf89654.png)

**Comment by ShawnHardwick** [comment]
I have my bot hosted in docker behind an nginx reverse proxy that connects externally successfully so I'm not sure if the "reverse proxy" part of this is applicable.

**Comment by P1-Ro** [comment]
@denverquane On Heroku it behaves exactly like it would behave with reverse proxy or load balancer. Instance is running with some internal port but it is reachable only over 80/443 from outside. I understand that running multiple shards is for better scalling but wouldn't that make horizontal scaling harder(if that od even needed)? 

@Plysm I did exactly same change

**Comment by dochan-consultis** [comment]
After reading more about scaling discord bot sharding is way to go and my proposal is totally not needed. You can close this.

**Comment by jasperduijn** [comment]
The new **EXT_PORT** variable fixed the issue for me.

**Comment by CarterBrehm** [comment]
@jasperduijn Can you explain a little more how you used EXT_PORT? From the documentation alone, I'm not sure what ports to use for PORT and EXT_PORT. I have my bot hosted in Heroku.

**Comment by CarterBrehm** [comment]
Putting this here for anyone else who is confused, because I managed to figure it out. I now have the discord bot working with all functionality (hosting, dual bot tokens, etc) in Heroku with the following config vars:

![Heroku Config Vars Screenshot](https://user-images.githubusercontent.com/26262673/95618870-5922e100-0a33-11eb-902b-1164568e1cdc.png)

In this picture, the DISCORD_BOT_TOKEN and DISCORD_BOT_TOKEN_2 vars are copied from the [Discord Developer Portal](https://discord.com/developers/applications), my EXT_PORT is set to 443 (although I'm sure it could be set to 80 as well), and my SERVER_URL was copied and pasted (sans the trailing slash) from further down the page in the section titled Domains. I didn't define a PORT, which means it's set at the default of 8123.
