### ISSUE TITLE
bring back the reactions

### ISSUE THREAD

**Issue by aflacc** [denverquane/amongusdiscord#137]
i have no idea how to use this new version

**Comment by denverquane** [comment]
You haven't provided any details whatsoever as to what problem you're encountering. I can't help you if you don't provide any details

**Comment by aflacc** [comment]
![image](https://user-images.githubusercontent.com/60161366/95796891-e881fb80-0ca2-11eb-9577-ea6dc164fbed.png)
Theres not reactions now

**Comment by denverquane** [comment]
Get into a lobby, why would there be reactions at the main menu

**Comment by aflacc** [comment]
I am in a lobby right now
![image](https://user-images.githubusercontent.com/60161366/95797050-59c1ae80-0ca3-11eb-96a5-4cc9ae01fd78.png)
still not working

**Comment by denverquane** [comment]
What do your capture logs say? Please don't say you're on cracked or beta among us

**Comment by aflacc** [comment]
not on cracked among us but i think it may think i am if thats the case

**Comment by aflacc** [comment]
and the capture logs:
`[ClientSocket]: Connection lost!
[ClientSocket]: Connected successfully!
[ClientSocket]: Connection code (1F2D4A1D) sent to server.
[GameMemReader]: State changed to MENU
`

**Comment by slang25** [comment]
The latest version is working here. Is this the Steam distributed version?

**Comment by aflacc** [comment]
i mean i got it from gift yea

**Comment by ThinkingParadox** [comment]
Do you see the emojis on the discord server? If you go to Server Settings > Emoji, you should see something similar to this: 
![image](https://user-images.githubusercontent.com/9680453/95816834-04f75580-0cee-11eb-92cd-a696b947b1c7.png)

Also might want to post more logs. Logs around when the bot starts or starts a game. You can crop out the important info like User IDs, guild IDs, and any custom URLs that you have. The line you sent was not really much since that is after you connected the capture. The emoji part should be before that either when you run the new command or when you launch the bot. 
![image](https://user-images.githubusercontent.com/9680453/95816818-f872fd00-0ced-11eb-8543-1c6a15fecfe5.png)
