### ISSUE TITLE
tesseract file not found but in right location

### ISSUE THREAD

**Issue by upishanker** [denverquane/amongusdiscord#14]
when run. amongusdiscord,exe says that the tesseract file cannot be found but it is in the right location
![Screenshot (6)](https://user-images.githubusercontent.com/64914758/93488477-06d72000-f8cc-11ea-89e5-203bee69b463.png)
![Screenshot (7)](https://user-images.githubusercontent.com/64914758/93488480-076fb680-f8cc-11ea-93f5-df5b14046c02.png)
![Screenshot (5)](https://user-images.githubusercontent.com/64914758/93488482-076fb680-f8cc-11ea-952c-ab76c2799d7c.png)

**Comment by harrygallagher4** [comment]
It looks like you made some typos when installing Tesseract & configuring the bot. It's spelled "tessEract" rather than "tessAract"

Your Tesseract folder is: `C:\Program Files\Tessaract-OCR` (spelled incorrectly)
Your tesseract.exe is: `C:\Program Files\Tessaract-OCR\tesseract.exe` (folder spelled incorrectly, exe spelled correctly)
The bot is looking for: `C:\Program Files\Tessaract-OCR\tessaract.exe` (both spelled incorrectly)

Fixing the typos should fix it, or you could leave the folder spelled wrong but configure the bot to look for the right exe.

**Comment by alzeric** [comment]
When in doubt click the URL bar in Windows Explorer and Copy and Paste the location.
