### ISSUE TITLE
Heroku: PORT config vars conflicts with reserved name

### ISSUE THREAD

**Issue by alvsc** [denverquane/amongusdiscord#142]
It seems like Heroku has its own reserved config vars named "PORT" which conflicts with bot's environment var "PORT".
This creates a problem when trying to specify and provide the bot with multiple ports to run as shards.

Steps to Recreate:
1) Deploy to Heroku
2) Set Config Vars to: 
DISCORD_BOT_TOKEN = xx
DISCORD_BOT_TOKEN2 = xxx
EXT_PORT = 443
GOVERSION = 1.15
NUM_SHARDS = 2
SERVER_URL = https://{yourappname}.herokuapp.com
PORT = 8123, 8124
3) Check logs
4) You will be presented with the follow errors:
```
app[web.1]: 2020/10/12 08:24:05 Program exited with the following error:
app[web.1]: 2020/10/12 08:24:05 the number of shards does not match the number of ports provided
```
Root Cause: Heroku sets PORT 80 & 443 as part of the environment automatically and is reserved for Heroku:
https://stackoverflow.com/questions/32826491/heroku-not-using-defined-port-environment-var

Suggestion: Update bot code to use a non Heroku reserved variable names i.e. bot.PORT or BOT_PORT.

**Comment by denverquane** [comment]
The exact reason I switched from `SERVER_PORT` to `PORT` was because of Heroku users' suggestions... (╯°□°）╯︵ ┻━┻

But, I am removing the ability to run the app as multiple shards *in a single instance* in the next update. The current solution is ugly and brittle (if one shard crashes, all will go down), and I think a proper multiple-container/app is really the only safe solution while we still discover bugs and inconsistencies with the current app

**Comment by alvsc** [comment]
Just a note: not an expert on Heroku, just learned about it.
I think I misunderstood the documentation, I wanted to run 2 bots on a single instance, and I mistakenly thought I needed 2 ports. It turns out shards != # of ports, as they are 2 separate things. I managed to get 2 bots running on1 Heroku app by adding the 2nd token. Which is what I wanted to achieve, instead of having 2 inbound endpoints (shards)

You can close this this "issue", thanks for the reply :)
