### ISSUE TITLE
State doesn't transition from discussion to tasks

### ISSUE THREAD

**Issue by zweehn** [denverquane/amongusdiscord#40]
When trying your bot out, i noticed that while in game, the current state does not change to tasks after a discussion ends.

I used the 2.0 Prerelease but have the same problem when building the current master branch of AmongUsCapture from source

It seems that the meetingHudState doesn't get updated properly, it stays < 4

**Comment by denverquane** [comment]
We haven't fully identified the cause yet, but newest 2.0.1 pre-release adds a `.au force` command to allow you to force the server to transition if it didn't detect it on the client. For ex, `.au force task`, `discuss`, `lobby`, or their single-letter equivalents `t`/`d`/`l`

**Comment by rorosaurus** [comment]
I can confirm this issue as well. Based on my testing, I think there are two parts. It seems like these two issues can happen independently of each other. These issues are probably better suited for the capture exe repo.

1) State transitions sometimes are not happening at all. (Anecdotally, this issue seems to only happen when I join a friend's game - not when I host my own lobby.)

2) Sometimes games accidentally start off in discussion mode instead of tasks. (When I host the lobby myself, this only happens for the first game - all subsequent games correctly start off in task state.)

(Lobby state changes always happen correctly.)

**Comment by LambdaTiger33** [comment]
I can confirm this problem as well
i have custom permissions on the text channel im using the bot on though not sure if this affects it.
also can confirm what rorosaurus said: games sometimes start in discussion phase instead of tasks
